apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test23-componentos
  namespace: test2
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-appstudioapp
        appstudio.openshift.io/component: test23-componentos
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test23-componentos-
      labels:
        appstudio.openshift.io/application: test-appstudioapp
        appstudio.openshift.io/component: test23-componentos
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: test2
    spec:
      params:
      - name: git-url
        value: https://github.com/psturc-org/hacbs-test-project
      - name: output-image
        value: quay.io/psturc/test-images:jvm-test123-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/psturc/pipeline-java-builder:hack2
        name: java-builder
      podTemplate:
        imagePullSecrets:
        - name: redhat-appstudio-registry-pull-secret
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
